### PR TITLE
version update Mascot to fix dimension issue

### PR DESCRIPTION
**Pull request by nicfel**

### CODE REVIEW

**Comment by rbouckaert** [comment]
Hi Nicola,

The packages.xml file should contain an entry for every version, to guarantee backward compatibility (see note at top of the file). This update just appears to update the entry. 

Also, packages.xml should only contain packages of published peer reviewed methods, and can go in packages-extra.xml otherwise. Perhaps, the paper is already published (I only found an biorxiv perprint)?

Cheers,

Remco

**Comment by nicfel** [comment]
Hi Remco,

The theory (derivations of the method and how it compares to other structured coalescent approaches) is described here https://doi.org/10.1093/molbev/msx186. Mascot contains however additional functionalities etc. explained here https://doi.org/10.1101/188516.

Cheers,
Nicola

**Comment by rbouckaert** [comment]
OK, good to see that it is already published! Still, the packages entry should not be replaced, but only added to:

**Comment by rbouckaert** [comment]
Superseded by #28

**Pull request closed without merging**
