### PR TITLE
removed SpeciesNetwork v0.12.2

### PR DESCRIPTION
**Pull request by zhangchicool**
I have removed unavailable version (v0.12.2) of SpeciesNetwork in packages2.6.xml.

### CODE REVIEW

**Comment by rbouckaert** [comment]
@zhangchicool What happened to SpeciesNetwork v0.12.2?
We would like to keep older versions of packages available in order to make runs replicable: if someone published an analysis with say version v0.1.0 of a packages, but the package has since been upgraded to v0.2.0, it cannot be guaranteed that the analysis still produces the same results. Even though there may be bug fixes in v0.2.0, and v0.1.0 may actually produce wrong results, given the analysis is published, it should be reproducable with the same software.

**Comment by zhangchicool** [comment]
Hi Remco,
SpeciesNetwork v0.12.2 indeed contains a bug that prevents sampling a parameter, meaning that parameter is fixed to the initial state. It is not a serious bug, but i think reproducing this is not meaningful. I'd like to force users to use v0.13.0 (or newer) instead.
Anyway, I have removed the release of v0.12.2, and only kept v0.13.0 release in my GitHub page, which is compatible with BEAST 2.5.x and 2.6.x. So the link to v0.12.2 is not working anymore. If people want to use v0.12.2, they can compile from the source code (under the tag of 0.12.2), so they can still reproduce things if they really want to. 
Chi

**Comment by rbouckaert** [comment]
Hi Chi,

Thanks for the explanation. Bugs happen all the time, and of course we are aiming for not having any, but inevitably we keep on discovering things that are not what they should be. However, for replicability of science it is important to make it as easy as possible to reproduce published work, especially when we know there were some bugs: if it is not significant, it won't impact the results, but the only way to know is to run with and without the fix.

Asking users to rebuild from source to get a specific version does not seem very user friendly. Also, just because the version is missing from CBAN does not mean people cannot use it if already installed. BEAUti automatically checks for new versions (unless the user does not want this) so users will be prompted for new versions. This also means that by default the latest version will be installed, and you have to go through some effort to install older versions.

Anyway, I would appreciate it if you could reinstate v0.12.2 for the above reasons, instead of deleting them altogether.

Cheers, Remco

**Comment by zhangchicool** [comment]
I've brought the file back, sorry for the trouble.

**Pull request closed without merging**
