### PR TITLE
Adds BSSVS type sampling to MASCOT

### PR DESCRIPTION
**Pull request by nicfel**

### CODE REVIEW

**Comment by Jinglu1982** [comment]
Hi Nicola, 
Does this mean I just use the MascotBSSVS template which has been included in beast2.5 and not need to modify the xml files generated using Mascot? If not, could you include a template for adding the BSSVs in the xml file.  I tried to use the MascotBSSVS template and got a problem on running the xml file. The log file shows:

**'too many iterations, erturn negative infinity
-1.2346927253745496E-24
[0.0, 31.500190648934005, 0.0, 0.0, 11.391871269784282]
[0.0, 0.0, 38.78438598443175, 3.921281832428196, 0.0]
[5.556795016988878, 0.0, 0.0, 0.0, 0.0]
ode calculation stuck, return negative infinity'**

Do you know what the problem is? Many thanks.

Best,
Jing

**Comment by nicfel** [comment]
Hi Jing,

Sorry for the bad error reporting, I'll fix this in the future.

This is probably and error with the ODE integration that can occur if coalescence (1/Ne) or migration rates get too high. Maybe having a stronger prior on e.g. the Ne's helps.

Let me know if the issue persists.
Best,
Nicola

**Comment by Jinglu1982** [comment]
Hi Nicola,

Thanks for the quick reply. I tried the Mascot without BSSVs. It works but takes a extremly long time (52m/Msamples, time is still increasing with sampling). With the BSSVs, the error still occured even though the stronger prior was set on Ne based on previous analysis. I have attached xml files for Mascot with or without BSSVs. Would you mind taking a little time to help me check? Many thanks. 
[GII17_1801_HKY_Mascot_300M.xml.txt](https://github.com/CompEvol/CBAN/files/2139781/GII17_1801_HKY_Mascot_300M.xml.txt)

[GII17_1801_HKY_Mascot_BSSVs_300M.xml.txt](https://github.com/CompEvol/CBAN/files/2139763/GII17_1801_HKY_Mascot_BSSVs_300M.xml.txt)

Ps: I don't think it is a big dataset, and whether 5 dimesions are too many for Mascot to handle?

Best,
Jing

**Comment by Jinglu1982** [comment]
And now the Mascot run (without BSSVs) also occured errors as many iterations return negative infinity.

**Pull request merged**
